# --- CORE SIMULATION PERIOD ---------------------------------
years:
  start: 2000          # earliest index procedure we have data for
  simulate_from: 2025  # first year we forecast ViV need
  end: 2035

# --- PROCEDURE COUNTS (external CSV paths) ------------------
procedure_counts:
  redo_savr: data/registry_redo_savr.csv
  tavi:       data/registry_tavi.csv

# --- VALVE DURABILITY ASSUMPTIONS ---------------------------
durability:
  savr_bioprosthetic:
    lt70:     {mean: 10, sd: 5, weight: 1.0}   # weight=1 b/c single mode inside age stratum
    gte70:    {mean: 17, sd: 5, weight: 1.0}
  tavi:
    early:    {mean: 4,  sd: 1.5, weight: 0.20}
    late:     {mean: 11.5, sd: 3.5, weight: 0.80}


# --- REDO-SURGERY RATES (literature defaults) ---------------
redo_rates:
  savr_after_savr: 0.04   # 4 % of failed SAVR go back to open surgery
  savr_after_tavi: 0.01   # 1 % of failed TAVI are treated with redo-SAVR


# --- SURVIVAL / LIFE-EXPECTANCY -----------------------------
survival_curves:
  low_risk:            {median: 11, sd: 3}
  int_high_risk:       {median: 6,  sd: 2}

risk_mix:
  savr: {low: 0.85, ih: 0.15}
  tavi:
    2014-2019: {low: 0.0,  ih: 1.0}
    2019-2024: {low: 0.33, ih: 0.67}
    2024-2035: {low: 0.50, ih: 0.50}

# --- VIV PENETRATION ASSUMPTIONS ----------------------------
penetration:
  tavi_in_tavi:
    2007-2022: 0.10
    2035:      0.60          # linear interpolation in-between
  tavi_in_savr:
    2007-2022: 0.60
    2035:      0.80

# --- REDO-SURGERY ADJUSTMENTS -------------------------------
redo_procedures_source: data/redo_trends.csv

# --- MONTE CARLO SETTINGS ----------------------------------
simulation:
  n_runs:   20
  rng_seed: 20250713

outputs:
  csv: out/viv_forecast.csv
  figs: out/figs/
